// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CustomerType.
const (
	CustomerTypeBusiness CustomerType = "business"
	CustomerTypePersonal CustomerType = "personal"
)

// Defines values for CustomerInputType.
const (
	CustomerInputTypeBusiness CustomerInputType = "business"
	CustomerInputTypePersonal CustomerInputType = "personal"
)

// Defines values for LeadStatus.
const (
	LeadStatusClosed    LeadStatus = "closed"
	LeadStatusContacted LeadStatus = "contacted"
	LeadStatusConverted LeadStatus = "converted"
	LeadStatusNew       LeadStatus = "new"
)

// Defines values for OrderChannel.
const (
	OrderChannelFb      OrderChannel = "fb"
	OrderChannelPhone   OrderChannel = "phone"
	OrderChannelWebsite OrderChannel = "website"
	OrderChannelZalo    OrderChannel = "zalo"
)

// Defines values for OrderStatus.
const (
	OrderStatusCancelled  OrderStatus = "cancelled"
	OrderStatusConfirmed  OrderStatus = "confirmed"
	OrderStatusDelivering OrderStatus = "delivering"
	OrderStatusDone       OrderStatus = "done"
	OrderStatusNew        OrderStatus = "new"
)

// Defines values for OrderDetailChannel.
const (
	OrderDetailChannelFb      OrderDetailChannel = "fb"
	OrderDetailChannelPhone   OrderDetailChannel = "phone"
	OrderDetailChannelWebsite OrderDetailChannel = "website"
	OrderDetailChannelZalo    OrderDetailChannel = "zalo"
)

// Defines values for OrderDetailStatus.
const (
	Cancelled  OrderDetailStatus = "cancelled"
	Confirmed  OrderDetailStatus = "confirmed"
	Delivering OrderDetailStatus = "delivering"
	Done       OrderDetailStatus = "done"
	New        OrderDetailStatus = "new"
)

// Defines values for OrderInputChannel.
const (
	Fb      OrderInputChannel = "fb"
	Phone   OrderInputChannel = "phone"
	Website OrderInputChannel = "website"
	Zalo    OrderInputChannel = "zalo"
)

// Defines values for ProductStatus.
const (
	Available ProductStatus = "available"
	Hidden    ProductStatus = "hidden"
	SoldOut   ProductStatus = "sold_out"
)

// Defines values for ProductType.
const (
	GiftBox    ProductType = "gift_box"
	SingleCake ProductType = "single_cake"
)

// AdminMe defines model for AdminMe.
type AdminMe struct {
	Email string             `json:"email"`
	Id    openapi_types.UUID `json:"id"`
	Name  *string            `json:"name"`
}

// ConvertLeadResult defines model for ConvertLeadResult.
type ConvertLeadResult struct {
	// OrderCode Mã đơn sinh tự động, vd "MC-20260717-AB12"
	OrderCode string             `json:"order_code"`
	OrderId   openapi_types.UUID `json:"order_id"`
}

// Customer defines model for Customer.
type Customer struct {
	Address   *string            `json:"address"`
	Company   *string            `json:"company"`
	CreatedAt time.Time          `json:"created_at"`
	Email     *string            `json:"email"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
	Note      *string            `json:"note"`
	Phone     *string            `json:"phone"`
	Type      CustomerType       `json:"type"`
}

// CustomerType defines model for Customer.Type.
type CustomerType string

// CustomerCreated defines model for CustomerCreated.
type CustomerCreated struct {
	Id openapi_types.UUID `json:"id"`
}

// CustomerInput defines model for CustomerInput.
type CustomerInput struct {
	Address *string `json:"address"`
	Company *string `json:"company"`

	// Email Email (tùy chọn). Nếu có phải chứa @ và domain.
	Email *string `json:"email"`

	// Name Tên khách hàng, bắt buộc, không rỗng
	Name string  `json:"name"`
	Note *string `json:"note"`

	// Phone SĐT Việt Nam (tùy chọn). Nếu có phải đúng định dạng VN.
	Phone *string `json:"phone"`

	// Type Loại khách. Sai enum → 400.
	Type CustomerInputType `json:"type"`
}

// CustomerInputType Loại khách. Sai enum → 400.
type CustomerInputType string

// CustomerList defines model for CustomerList.
type CustomerList struct {
	Items []Customer `json:"items"`

	// Total Tổng số khách hàng (không phân trang)
	Total int64 `json:"total"`
}

// Dashboard defines model for Dashboard.
type Dashboard struct {
	// NewLeads Số leads mới (status='new')
	NewLeads int64 `json:"new_leads"`

	// ProcessingOrders Số đơn đang xử lý (status ∈ {confirmed, delivering})
	ProcessingOrders int64 `json:"processing_orders"`

	// RevenueThisMonth Doanh thu tháng hiện tại — tổng total các đơn status='done' tạo trong tháng, neo múi giờ Việt Nam (Asia/Ho_Chi_Minh).
	RevenueThisMonth int64 `json:"revenue_this_month"`
}

// Error defines model for Error.
type Error struct {
	Error string `json:"error"`
}

// Health defines model for Health.
type Health struct {
	Status string `json:"status"`
}

// ImageUploadResult defines model for ImageUploadResult.
type ImageUploadResult struct {
	// ImageUrl Đường dẫn public của ảnh, vd "/uploads/<uuid>.png"
	ImageUrl string `json:"image_url"`
}

// Lead defines model for Lead.
type Lead struct {
	CreatedAt time.Time          `json:"created_at"`
	Id        openapi_types.UUID `json:"id"`
	Message   *string            `json:"message"`
	Name      string             `json:"name"`

	// OrderId Đơn đã convert từ lead này (null nếu chưa convert)
	OrderId         *openapi_types.UUID `json:"order_id"`
	Phone           string              `json:"phone"`
	ProductInterest *string             `json:"product_interest"`

	// Source Nguồn lead (website | phone | zalo | fb | ...)
	Source string     `json:"source"`
	Status LeadStatus `json:"status"`
}

// LeadStatus defines model for Lead.Status.
type LeadStatus string

// LeadCreated defines model for LeadCreated.
type LeadCreated struct {
	Id openapi_types.UUID `json:"id"`
}

// LeadInput defines model for LeadInput.
type LeadInput struct {
	// Message Lời nhắn
	Message *string `json:"message"`

	// Name Tên khách hàng (bắt buộc)
	Name string `json:"name"`

	// Phone Số điện thoại Việt Nam (bắt buộc)
	Phone string `json:"phone"`

	// ProductInterest Sản phẩm khách quan tâm
	ProductInterest *string `json:"product_interest"`
}

// LeadList defines model for LeadList.
type LeadList struct {
	Items []Lead `json:"items"`

	// Total Tổng số lead (không phân trang)
	Total int64 `json:"total"`
}

// LeadStatusInput defines model for LeadStatusInput.
type LeadStatusInput struct {
	// Status Trạng thái mới. Hợp lệ- new | contacted | converted | closed
	Status string `json:"status"`
}

// LoginInput defines model for LoginInput.
type LoginInput struct {
	// Email Email admin
	Email string `json:"email"`

	// Password Mật khẩu (không log, không lưu plaintext)
	Password string `json:"password"`
}

// LoginResult defines model for LoginResult.
type LoginResult struct {
	Ok bool `json:"ok"`
}

// Order defines model for Order.
type Order struct {
	Channel         OrderChannel        `json:"channel"`
	Code            string              `json:"code"`
	CreatedAt       time.Time           `json:"created_at"`
	CustomerId      *openapi_types.UUID `json:"customer_id"`
	DeliveryAddress *string             `json:"delivery_address"`
	DeliveryDate    *openapi_types.Date `json:"delivery_date"`
	Discount        int64               `json:"discount"`
	Id              openapi_types.UUID  `json:"id"`
	Note            *string             `json:"note"`
	Status          OrderStatus         `json:"status"`
	Subtotal        int64               `json:"subtotal"`
	Total           int64               `json:"total"`
}

// OrderChannel defines model for Order.Channel.
type OrderChannel string

// OrderStatus defines model for Order.Status.
type OrderStatus string

// OrderCreated defines model for OrderCreated.
type OrderCreated struct {
	// Code Mã đơn sinh tự động, vd "MC-20260717-AB12"
	Code string             `json:"code"`
	Id   openapi_types.UUID `json:"id"`
}

// OrderDetail defines model for OrderDetail.
type OrderDetail struct {
	Channel         OrderDetailChannel  `json:"channel"`
	Code            string              `json:"code"`
	CreatedAt       time.Time           `json:"created_at"`
	CustomerId      *openapi_types.UUID `json:"customer_id"`
	DeliveryAddress *string             `json:"delivery_address"`
	DeliveryDate    *openapi_types.Date `json:"delivery_date"`
	Discount        int64               `json:"discount"`
	Id              openapi_types.UUID  `json:"id"`
	Items           []OrderItem         `json:"items"`
	Note            *string             `json:"note"`
	Status          OrderDetailStatus   `json:"status"`
	Subtotal        int64               `json:"subtotal"`
	Total           int64               `json:"total"`
}

// OrderDetailChannel defines model for OrderDetail.Channel.
type OrderDetailChannel string

// OrderDetailStatus defines model for OrderDetail.Status.
type OrderDetailStatus string

// OrderInput defines model for OrderInput.
type OrderInput struct {
	// Channel Kênh đặt hàng
	Channel OrderInputChannel `json:"channel"`

	// CustomerId Khách hàng (tùy chọn — gắn thủ công)
	CustomerId      *openapi_types.UUID `json:"customer_id"`
	DeliveryAddress *string             `json:"delivery_address"`
	DeliveryDate    *openapi_types.Date `json:"delivery_date"`

	// Discount Giảm giá VND ≥ 0 (mặc định 0). Vượt tổng tiền hàng → 400.
	Discount *int64 `json:"discount"`

	// Items Ít nhất 1 dòng đơn, tối đa 100
	Items []OrderItemInput `json:"items"`
	Note  *string          `json:"note"`
}

// OrderInputChannel Kênh đặt hàng
type OrderInputChannel string

// OrderItem defines model for OrderItem.
type OrderItem struct {
	Id        openapi_types.UUID  `json:"id"`
	ProductId *openapi_types.UUID `json:"product_id"`

	// ProductName Snapshot tên sản phẩm tại thời điểm đặt
	ProductName string `json:"product_name"`
	Quantity    int    `json:"quantity"`

	// UnitPrice Snapshot đơn giá tại thời điểm đặt (VND)
	UnitPrice int64 `json:"unit_price"`
}

// OrderItemInput defines model for OrderItemInput.
type OrderItemInput struct {
	// ProductId Sản phẩm đặt. Không tồn tại → 400 (rollback toàn bộ đơn).
	ProductId openapi_types.UUID `json:"product_id"`

	// Quantity Số lượng, phải > 0 và ≤ 10000
	Quantity int `json:"quantity"`
}

// OrderList defines model for OrderList.
type OrderList struct {
	Items []Order `json:"items"`

	// Total Tổng số đơn (không phân trang)
	Total int64 `json:"total"`
}

// OrderStatusInput defines model for OrderStatusInput.
type OrderStatusInput struct {
	// Status Trạng thái mới. Hợp lệ- new | confirmed | delivering | done | cancelled
	Status string `json:"status"`
}

// Product defines model for Product.
type Product struct {
	// Badge Nhãn marketing (vd "Bán chạy", "Mới"), null nếu không có
	Badge *string `json:"badge"`

	// CompareAtPrice Giá gốc để so sánh (VND). Nếu > price → hiện giá gạch + % giảm. Null nếu không khuyến mãi.
	CompareAtPrice *int64             `json:"compare_at_price"`
	Description    *string            `json:"description"`
	DisplayOrder   int                `json:"display_order"`
	Id             openapi_types.UUID `json:"id"`
	ImageUrl       *string            `json:"image_url"`
	Name           string             `json:"name"`

	// Price Giá VND, số nguyên
	Price  int64         `json:"price"`
	Slug   string        `json:"slug"`
	Status ProductStatus `json:"status"`

	// Subtitle Nhãn phân loại nhỏ in hoa trên tên (vd "Hộp thiếc cao cấp"), null nếu không có
	Subtitle *string     `json:"subtitle"`
	Type     ProductType `json:"type"`
}

// ProductStatus defines model for Product.Status.
type ProductStatus string

// ProductType defines model for Product.Type.
type ProductType string

// ProductInput defines model for ProductInput.
type ProductInput struct {
	Badge          *string `json:"badge"`
	CompareAtPrice *int64  `json:"compare_at_price"`
	Description    *string `json:"description"`

	// DisplayOrder Thứ tự hiển thị (mặc định 0 nếu bỏ trống)
	DisplayOrder *int    `json:"display_order"`
	ImageUrl     *string `json:"image_url"`

	// Name Tên sản phẩm (bắt buộc, không rỗng)
	Name string `json:"name"`

	// Price Giá VND, số nguyên ≥ 0
	Price int64 `json:"price"`

	// Slug Định danh URL (duy nhất). Trùng → 409.
	Slug string `json:"slug"`

	// Status Trạng thái. Hợp lệ- available | sold_out | hidden
	Status   string  `json:"status"`
	Subtitle *string `json:"subtitle"`

	// Type Loại sản phẩm. Hợp lệ- gift_box | single_cake
	Type string `json:"type"`
}

// ListAdminCustomersParams defines parameters for ListAdminCustomers.
type ListAdminCustomersParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListAdminLeadsParams defines parameters for ListAdminLeads.
type ListAdminLeadsParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// ListAdminOrdersParams defines parameters for ListAdminOrders.
type ListAdminOrdersParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// UploadProductImageMultipartBody defines parameters for UploadProductImage.
type UploadProductImageMultipartBody struct {
	File openapi_types.File `json:"file"`
}

// CreateCustomerJSONRequestBody defines body for CreateCustomer for application/json ContentType.
type CreateCustomerJSONRequestBody = CustomerInput

// UpdateCustomerJSONRequestBody defines body for UpdateCustomer for application/json ContentType.
type UpdateCustomerJSONRequestBody = CustomerInput

// UpdateLeadStatusJSONRequestBody defines body for UpdateLeadStatus for application/json ContentType.
type UpdateLeadStatusJSONRequestBody = LeadStatusInput

// CreateOrderJSONRequestBody defines body for CreateOrder for application/json ContentType.
type CreateOrderJSONRequestBody = OrderInput

// UpdateOrderStatusJSONRequestBody defines body for UpdateOrderStatus for application/json ContentType.
type UpdateOrderStatusJSONRequestBody = OrderStatusInput

// CreateProductJSONRequestBody defines body for CreateProduct for application/json ContentType.
type CreateProductJSONRequestBody = ProductInput

// UpdateProductJSONRequestBody defines body for UpdateProduct for application/json ContentType.
type UpdateProductJSONRequestBody = ProductInput

// UploadProductImageMultipartRequestBody defines body for UploadProductImage for multipart/form-data ContentType.
type UploadProductImageMultipartRequestBody UploadProductImageMultipartBody

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginInput

// CreateLeadJSONRequestBody defines body for CreateLead for application/json ContentType.
type CreateLeadJSONRequestBody = LeadInput

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Danh sách khách hàng cho admin (phân trang)
	// (GET /admin/customers)
	ListAdminCustomers(w http.ResponseWriter, r *http.Request, params ListAdminCustomersParams)
	// Tạo khách hàng
	// (POST /admin/customers)
	CreateCustomer(w http.ResponseWriter, r *http.Request)
	// Chi tiết khách hàng
	// (GET /admin/customers/{id})
	GetAdminCustomer(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Cập nhật khách hàng
	// (PUT /admin/customers/{id})
	UpdateCustomer(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Tổng quan admin (dashboard)
	// (GET /admin/dashboard)
	GetAdminDashboard(w http.ResponseWriter, r *http.Request)
	// Danh sách leads cho admin (phân trang)
	// (GET /admin/leads)
	ListAdminLeads(w http.ResponseWriter, r *http.Request, params ListAdminLeadsParams)
	// Cập nhật trạng thái lead
	// (PATCH /admin/leads/{id})
	UpdateLeadStatus(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Convert lead thành đơn nháp
	// (POST /admin/leads/{id}/convert)
	ConvertLead(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Thông tin admin đang đăng nhập
	// (GET /admin/me)
	GetAdminMe(w http.ResponseWriter, r *http.Request)
	// Danh sách đơn hàng cho admin (phân trang)
	// (GET /admin/orders)
	ListAdminOrders(w http.ResponseWriter, r *http.Request, params ListAdminOrdersParams)
	// Tạo đơn hàng (nhập tay)
	// (POST /admin/orders)
	CreateOrder(w http.ResponseWriter, r *http.Request)
	// Chi tiết đơn hàng + các dòng
	// (GET /admin/orders/{id})
	GetAdminOrder(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Cập nhật trạng thái đơn hàng
	// (PATCH /admin/orders/{id})
	UpdateOrderStatus(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Danh sách sản phẩm cho admin (gồm cả hidden)
	// (GET /admin/products)
	ListAdminProducts(w http.ResponseWriter, r *http.Request)
	// Tạo sản phẩm mới
	// (POST /admin/products)
	CreateProduct(w http.ResponseWriter, r *http.Request)
	// Xóa (ẩn) sản phẩm
	// (DELETE /admin/products/{id})
	DeleteProduct(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Cập nhật sản phẩm
	// (PUT /admin/products/{id})
	UpdateProduct(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Upload ảnh sản phẩm
	// (POST /admin/products/{id}/image)
	UploadProductImage(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Đăng nhập admin
	// (POST /auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// Đăng xuất admin
	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// Health check
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
	// Tạo lead từ form liên hệ
	// (POST /leads)
	CreateLead(w http.ResponseWriter, r *http.Request)
	// Danh sách sản phẩm public
	// (GET /products)
	ListProducts(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Danh sách khách hàng cho admin (phân trang)
// (GET /admin/customers)
func (_ Unimplemented) ListAdminCustomers(w http.ResponseWriter, r *http.Request, params ListAdminCustomersParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Tạo khách hàng
// (POST /admin/customers)
func (_ Unimplemented) CreateCustomer(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Chi tiết khách hàng
// (GET /admin/customers/{id})
func (_ Unimplemented) GetAdminCustomer(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Cập nhật khách hàng
// (PUT /admin/customers/{id})
func (_ Unimplemented) UpdateCustomer(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Tổng quan admin (dashboard)
// (GET /admin/dashboard)
func (_ Unimplemented) GetAdminDashboard(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Danh sách leads cho admin (phân trang)
// (GET /admin/leads)
func (_ Unimplemented) ListAdminLeads(w http.ResponseWriter, r *http.Request, params ListAdminLeadsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Cập nhật trạng thái lead
// (PATCH /admin/leads/{id})
func (_ Unimplemented) UpdateLeadStatus(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Convert lead thành đơn nháp
// (POST /admin/leads/{id}/convert)
func (_ Unimplemented) ConvertLead(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Thông tin admin đang đăng nhập
// (GET /admin/me)
func (_ Unimplemented) GetAdminMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Danh sách đơn hàng cho admin (phân trang)
// (GET /admin/orders)
func (_ Unimplemented) ListAdminOrders(w http.ResponseWriter, r *http.Request, params ListAdminOrdersParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Tạo đơn hàng (nhập tay)
// (POST /admin/orders)
func (_ Unimplemented) CreateOrder(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Chi tiết đơn hàng + các dòng
// (GET /admin/orders/{id})
func (_ Unimplemented) GetAdminOrder(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Cập nhật trạng thái đơn hàng
// (PATCH /admin/orders/{id})
func (_ Unimplemented) UpdateOrderStatus(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Danh sách sản phẩm cho admin (gồm cả hidden)
// (GET /admin/products)
func (_ Unimplemented) ListAdminProducts(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Tạo sản phẩm mới
// (POST /admin/products)
func (_ Unimplemented) CreateProduct(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Xóa (ẩn) sản phẩm
// (DELETE /admin/products/{id})
func (_ Unimplemented) DeleteProduct(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Cập nhật sản phẩm
// (PUT /admin/products/{id})
func (_ Unimplemented) UpdateProduct(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Upload ảnh sản phẩm
// (POST /admin/products/{id}/image)
func (_ Unimplemented) UploadProductImage(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Đăng nhập admin
// (POST /auth/login)
func (_ Unimplemented) Login(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Đăng xuất admin
// (POST /auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health check
// (GET /healthz)
func (_ Unimplemented) GetHealthz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Tạo lead từ form liên hệ
// (POST /leads)
func (_ Unimplemented) CreateLead(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Danh sách sản phẩm public
// (GET /products)
func (_ Unimplemented) ListProducts(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListAdminCustomers operation middleware
func (siw *ServerInterfaceWrapper) ListAdminCustomers(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAdminCustomersParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAdminCustomers(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateCustomer operation middleware
func (siw *ServerInterfaceWrapper) CreateCustomer(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCustomer(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAdminCustomer operation middleware
func (siw *ServerInterfaceWrapper) GetAdminCustomer(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAdminCustomer(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateCustomer operation middleware
func (siw *ServerInterfaceWrapper) UpdateCustomer(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateCustomer(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAdminDashboard operation middleware
func (siw *ServerInterfaceWrapper) GetAdminDashboard(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAdminDashboard(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAdminLeads operation middleware
func (siw *ServerInterfaceWrapper) ListAdminLeads(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAdminLeadsParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAdminLeads(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateLeadStatus operation middleware
func (siw *ServerInterfaceWrapper) UpdateLeadStatus(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateLeadStatus(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ConvertLead operation middleware
func (siw *ServerInterfaceWrapper) ConvertLead(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ConvertLead(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAdminMe operation middleware
func (siw *ServerInterfaceWrapper) GetAdminMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAdminMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAdminOrders operation middleware
func (siw *ServerInterfaceWrapper) ListAdminOrders(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAdminOrdersParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameter("form", true, false, "offset", r.URL.Query(), &params.Offset)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAdminOrders(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateOrder operation middleware
func (siw *ServerInterfaceWrapper) CreateOrder(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateOrder(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAdminOrder operation middleware
func (siw *ServerInterfaceWrapper) GetAdminOrder(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAdminOrder(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateOrderStatus operation middleware
func (siw *ServerInterfaceWrapper) UpdateOrderStatus(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateOrderStatus(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAdminProducts operation middleware
func (siw *ServerInterfaceWrapper) ListAdminProducts(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAdminProducts(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateProduct operation middleware
func (siw *ServerInterfaceWrapper) CreateProduct(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateProduct(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteProduct operation middleware
func (siw *ServerInterfaceWrapper) DeleteProduct(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteProduct(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateProduct operation middleware
func (siw *ServerInterfaceWrapper) UpdateProduct(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateProduct(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UploadProductImage operation middleware
func (siw *ServerInterfaceWrapper) UploadProductImage(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadProductImage(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateLead operation middleware
func (siw *ServerInterfaceWrapper) CreateLead(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateLead(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProducts operation middleware
func (siw *ServerInterfaceWrapper) ListProducts(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProducts(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/customers", wrapper.ListAdminCustomers)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/admin/customers", wrapper.CreateCustomer)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/customers/{id}", wrapper.GetAdminCustomer)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/admin/customers/{id}", wrapper.UpdateCustomer)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/dashboard", wrapper.GetAdminDashboard)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/leads", wrapper.ListAdminLeads)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/admin/leads/{id}", wrapper.UpdateLeadStatus)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/admin/leads/{id}/convert", wrapper.ConvertLead)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/me", wrapper.GetAdminMe)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/orders", wrapper.ListAdminOrders)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/admin/orders", wrapper.CreateOrder)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/orders/{id}", wrapper.GetAdminOrder)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/admin/orders/{id}", wrapper.UpdateOrderStatus)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/admin/products", wrapper.ListAdminProducts)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/admin/products", wrapper.CreateProduct)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/admin/products/{id}", wrapper.DeleteProduct)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/admin/products/{id}", wrapper.UpdateProduct)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/admin/products/{id}/image", wrapper.UploadProductImage)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.Login)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.GetHealthz)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/leads", wrapper.CreateLead)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/products", wrapper.ListProducts)
	})

	return r
}
