// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AdminUser struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Name         *string            `json:"name"`
	Role         string             `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Lead struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	Phone           string             `json:"phone"`
	Message         *string            `json:"message"`
	ProductInterest *string            `json:"product_interest"`
	Source          string             `json:"source"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Product struct {
	ID             pgtype.UUID        `json:"id"`
	Slug           string             `json:"slug"`
	Name           string             `json:"name"`
	Description    *string            `json:"description"`
	Price          int64              `json:"price"`
	Type           string             `json:"type"`
	Status         string             `json:"status"`
	ImageUrl       *string            `json:"image_url"`
	DisplayOrder   int32              `json:"display_order"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	Badge          *string            `json:"badge"`
	CompareAtPrice *int64             `json:"compare_at_price"`
	Subtitle       *string            `json:"subtitle"`
}
