// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAdminUser = `-- name: CreateAdminUser :one
INSERT INTO admin_users (email, password_hash, name, role)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password_hash, name, role, created_at
`

type CreateAdminUserParams struct {
	Email        string  `json:"email"`
	PasswordHash string  `json:"password_hash"`
	Name         *string `json:"name"`
	Role         string  `json:"role"`
}

func (q *Queries) CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) (AdminUser, error) {
	row := q.db.QueryRow(ctx, createAdminUser,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.Role,
	)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const createLead = `-- name: CreateLead :one
INSERT INTO leads (name, phone, message, product_interest)
VALUES ($1, $2, $3, $4)
RETURNING id, status
`

type CreateLeadParams struct {
	Name            string  `json:"name"`
	Phone           string  `json:"phone"`
	Message         *string `json:"message"`
	ProductInterest *string `json:"product_interest"`
}

type CreateLeadRow struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

// Tạo lead mới từ form liên hệ public. source mặc định 'website', status mặc định
// 'new' (REQ-LEAD-002/003). Trả id + status để handler xác nhận.
func (q *Queries) CreateLead(ctx context.Context, arg CreateLeadParams) (CreateLeadRow, error) {
	row := q.db.QueryRow(ctx, createLead,
		arg.Name,
		arg.Phone,
		arg.Message,
		arg.ProductInterest,
	)
	var i CreateLeadRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const getAdminUserByEmail = `-- name: GetAdminUserByEmail :one
SELECT id, email, password_hash, name, role, created_at
FROM admin_users
WHERE email = $1
`

func (q *Queries) GetAdminUserByEmail(ctx context.Context, email string) (AdminUser, error) {
	row := q.db.QueryRow(ctx, getAdminUserByEmail, email)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listVisibleProducts = `-- name: ListVisibleProducts :many
SELECT id, slug, name, description, price, type, status, image_url, display_order, created_at, updated_at, badge
FROM products
WHERE status != 'hidden'
ORDER BY display_order, created_at, id
`

// Sản phẩm public: ẩn status='hidden', sắp theo thứ tự hiển thị rồi thời gian tạo
// (REQ-PROD-001).
func (q *Queries) ListVisibleProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, listVisibleProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Type,
			&i.Status,
			&i.ImageUrl,
			&i.DisplayOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Badge,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
