// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCustomers = `-- name: CountCustomers :one
SELECT count(*) FROM customers
`

func (q *Queries) CountCustomers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCustomers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLeads = `-- name: CountLeads :one
SELECT count(*) FROM leads
`

func (q *Queries) CountLeads(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countLeads)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNewLeads = `-- name: CountNewLeads :one

SELECT count(*) FROM leads WHERE status = 'new'
`

// =====================================================================
// Dashboard (REQ-DASH-001)
// =====================================================================
func (q *Queries) CountNewLeads(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countNewLeads)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countOrders = `-- name: CountOrders :one
SELECT count(*) FROM orders
`

func (q *Queries) CountOrders(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOrders)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countProcessingOrders = `-- name: CountProcessingOrders :one
SELECT count(*) FROM orders WHERE status IN ('confirmed', 'delivering')
`

func (q *Queries) CountProcessingOrders(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countProcessingOrders)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdminUser = `-- name: CreateAdminUser :one
INSERT INTO admin_users (email, password_hash, name, role)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password_hash, name, role, created_at
`

type CreateAdminUserParams struct {
	Email        string  `json:"email"`
	PasswordHash string  `json:"password_hash"`
	Name         *string `json:"name"`
	Role         string  `json:"role"`
}

func (q *Queries) CreateAdminUser(ctx context.Context, arg CreateAdminUserParams) (AdminUser, error) {
	row := q.db.QueryRow(ctx, createAdminUser,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.Role,
	)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const createCustomer = `-- name: CreateCustomer :one

INSERT INTO customers (name, phone, email, company, address, type, note)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, phone, email, company, address, type, note, created_at, updated_at
`

type CreateCustomerParams struct {
	Name    string  `json:"name"`
	Phone   *string `json:"phone"`
	Email   *string `json:"email"`
	Company *string `json:"company"`
	Address *string `json:"address"`
	Type    string  `json:"type"`
	Note    *string `json:"note"`
}

// =====================================================================
// Customers (REQ-CUST-001)
// =====================================================================
func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.Company,
		arg.Address,
		arg.Type,
		arg.Note,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Company,
		&i.Address,
		&i.Type,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLead = `-- name: CreateLead :one
INSERT INTO leads (name, phone, message, product_interest)
VALUES ($1, $2, $3, $4)
RETURNING id, status
`

type CreateLeadParams struct {
	Name            string  `json:"name"`
	Phone           string  `json:"phone"`
	Message         *string `json:"message"`
	ProductInterest *string `json:"product_interest"`
}

type CreateLeadRow struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

// Tạo lead mới từ form liên hệ public. source mặc định 'website', status mặc định
// 'new' (REQ-LEAD-002/003). Trả id + status để handler xác nhận.
func (q *Queries) CreateLead(ctx context.Context, arg CreateLeadParams) (CreateLeadRow, error) {
	row := q.db.QueryRow(ctx, createLead,
		arg.Name,
		arg.Phone,
		arg.Message,
		arg.ProductInterest,
	)
	var i CreateLeadRow
	err := row.Scan(&i.ID, &i.Status)
	return i, err
}

const createOrder = `-- name: CreateOrder :one

INSERT INTO orders (code, customer_id, channel, status, subtotal, discount, total, delivery_date, delivery_address, note)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, code, customer_id, channel, status, subtotal, discount, total, delivery_date, delivery_address, note, created_at, updated_at
`

type CreateOrderParams struct {
	Code            string      `json:"code"`
	CustomerID      pgtype.UUID `json:"customer_id"`
	Channel         string      `json:"channel"`
	Status          string      `json:"status"`
	Subtotal        int64       `json:"subtotal"`
	Discount        int64       `json:"discount"`
	Total           int64       `json:"total"`
	DeliveryDate    pgtype.Date `json:"delivery_date"`
	DeliveryAddress *string     `json:"delivery_address"`
	Note            *string     `json:"note"`
}

// =====================================================================
// Orders + order_items (REQ-ORD-001/003/004)
// =====================================================================
func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.Code,
		arg.CustomerID,
		arg.Channel,
		arg.Status,
		arg.Subtotal,
		arg.Discount,
		arg.Total,
		arg.DeliveryDate,
		arg.DeliveryAddress,
		arg.Note,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.CustomerID,
		&i.Channel,
		&i.Status,
		&i.Subtotal,
		&i.Discount,
		&i.Total,
		&i.DeliveryDate,
		&i.DeliveryAddress,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (order_id, product_id, product_name, unit_price, quantity)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, order_id, product_id, product_name, unit_price, quantity, created_at
`

type CreateOrderItemParams struct {
	OrderID     pgtype.UUID `json:"order_id"`
	ProductID   pgtype.UUID `json:"product_id"`
	ProductName string      `json:"product_name"`
	UnitPrice   int64       `json:"unit_price"`
	Quantity    int32       `json:"quantity"`
}

// Dòng đơn với snapshot product_name + unit_price (REQ-ORD-004).
func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.ProductName,
		arg.UnitPrice,
		arg.Quantity,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.ProductName,
		&i.UnitPrice,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (slug, name, description, price, type, status, image_url, display_order, badge, compare_at_price, subtitle)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, slug, name, description, price, type, status, image_url, display_order, created_at, updated_at, badge, compare_at_price, subtitle
`

type CreateProductParams struct {
	Slug           string  `json:"slug"`
	Name           string  `json:"name"`
	Description    *string `json:"description"`
	Price          int64   `json:"price"`
	Type           string  `json:"type"`
	Status         string  `json:"status"`
	ImageUrl       *string `json:"image_url"`
	DisplayOrder   int32   `json:"display_order"`
	Badge          *string `json:"badge"`
	CompareAtPrice *int64  `json:"compare_at_price"`
	Subtitle       *string `json:"subtitle"`
}

// Tạo sản phẩm (REQ-PROD-002). Validate (name/price/type/status/slug) ở tầng
// handler; ràng buộc CHECK + UNIQUE(slug) ở DB là lớp phòng thủ cuối.
func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Type,
		arg.Status,
		arg.ImageUrl,
		arg.DisplayOrder,
		arg.Badge,
		arg.CompareAtPrice,
		arg.Subtitle,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Type,
		&i.Status,
		&i.ImageUrl,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Badge,
		&i.CompareAtPrice,
		&i.Subtitle,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
UPDATE products
SET status = 'hidden', updated_at = now()
WHERE id = $1
`

// Xóa MỀM: đặt status='hidden'. An toàn hơn xóa cứng vì order_items tham chiếu
// product_id (giữ toàn vẹn lịch sử đơn hàng) (REQ-PROD-002).
func (q *Queries) DeleteProduct(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const getAdminUserByEmail = `-- name: GetAdminUserByEmail :one
SELECT id, email, password_hash, name, role, created_at
FROM admin_users
WHERE email = $1
`

func (q *Queries) GetAdminUserByEmail(ctx context.Context, email string) (AdminUser, error) {
	row := q.db.QueryRow(ctx, getAdminUserByEmail, email)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getAdminUserByID = `-- name: GetAdminUserByID :one
SELECT id, email, password_hash, name, role, created_at
FROM admin_users
WHERE id = $1
`

// Lấy admin theo id (dùng cho GET /admin/me sau khi middleware xác thực JWT).
func (q *Queries) GetAdminUserByID(ctx context.Context, id pgtype.UUID) (AdminUser, error) {
	row := q.db.QueryRow(ctx, getAdminUserByID, id)
	var i AdminUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getCustomer = `-- name: GetCustomer :one
SELECT id, name, phone, email, company, address, type, note, created_at, updated_at
FROM customers
WHERE id = $1
`

func (q *Queries) GetCustomer(ctx context.Context, id pgtype.UUID) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomer, id)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Company,
		&i.Address,
		&i.Type,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLead = `-- name: GetLead :one
SELECT id, name, phone, message, product_interest, source, status, created_at, order_id
FROM leads
WHERE id = $1
`

// Lấy 1 lead theo id (dùng cho convert lead → đơn: cần tên/SĐT/lời nhắn/nguồn/
// trạng thái để dựng đơn nháp và chặn convert 2 lần) (REQ-LEAD-005).
func (q *Queries) GetLead(ctx context.Context, id pgtype.UUID) (Lead, error) {
	row := q.db.QueryRow(ctx, getLead, id)
	var i Lead
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Message,
		&i.ProductInterest,
		&i.Source,
		&i.Status,
		&i.CreatedAt,
		&i.OrderID,
	)
	return i, err
}

const getOrder = `-- name: GetOrder :one
SELECT id, code, customer_id, channel, status, subtotal, discount, total, delivery_date, delivery_address, note, created_at, updated_at
FROM orders
WHERE id = $1
`

func (q *Queries) GetOrder(ctx context.Context, id pgtype.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.CustomerID,
		&i.Channel,
		&i.Status,
		&i.Subtotal,
		&i.Discount,
		&i.Total,
		&i.DeliveryDate,
		&i.DeliveryAddress,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, slug, name, description, price, type, status, image_url, display_order, created_at, updated_at, badge, compare_at_price, subtitle
FROM products
WHERE id = $1
`

func (q *Queries) GetProductByID(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Type,
		&i.Status,
		&i.ImageUrl,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Badge,
		&i.CompareAtPrice,
		&i.Subtitle,
	)
	return i, err
}

const listAllProducts = `-- name: ListAllProducts :many
SELECT id, slug, name, description, price, type, status, image_url, display_order, created_at, updated_at, badge, compare_at_price, subtitle
FROM products
ORDER BY display_order, created_at, id
`

// Sản phẩm cho admin: GỒM cả status='hidden'. Thứ tự TẤT ĐỊNH (display_order,
// created_at, id) để list ổn định giữa các lần gọi (REQ-PROD-002).
func (q *Queries) ListAllProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, listAllProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Type,
			&i.Status,
			&i.ImageUrl,
			&i.DisplayOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Badge,
			&i.CompareAtPrice,
			&i.Subtitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomers = `-- name: ListCustomers :many
SELECT id, name, phone, email, company, address, type, note, created_at, updated_at
FROM customers
ORDER BY created_at DESC, id
LIMIT $1 OFFSET $2
`

type ListCustomersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Danh sách khách hàng cho admin, phân trang (mới nhất trước).
func (q *Queries) ListCustomers(ctx context.Context, arg ListCustomersParams) ([]Customer, error) {
	rows, err := q.db.Query(ctx, listCustomers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Phone,
			&i.Email,
			&i.Company,
			&i.Address,
			&i.Type,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeadsAdmin = `-- name: ListLeadsAdmin :many

SELECT id, name, phone, message, product_interest, source, status, created_at, order_id
FROM leads
ORDER BY created_at DESC, id
LIMIT $1 OFFSET $2
`

type ListLeadsAdminParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// =====================================================================
// Leads admin (REQ-LEAD-004/005)
// =====================================================================
// Danh sách lead cho admin, phân trang (mới nhất trước).
func (q *Queries) ListLeadsAdmin(ctx context.Context, arg ListLeadsAdminParams) ([]Lead, error) {
	rows, err := q.db.Query(ctx, listLeadsAdmin, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Lead
	for rows.Next() {
		var i Lead
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Phone,
			&i.Message,
			&i.ProductInterest,
			&i.Source,
			&i.Status,
			&i.CreatedAt,
			&i.OrderID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderItemsByOrder = `-- name: ListOrderItemsByOrder :many
SELECT id, order_id, product_id, product_name, unit_price, quantity, created_at
FROM order_items
WHERE order_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListOrderItemsByOrder(ctx context.Context, orderID pgtype.UUID) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItemsByOrder, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.ProductName,
			&i.UnitPrice,
			&i.Quantity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrders = `-- name: ListOrders :many
SELECT id, code, customer_id, channel, status, subtotal, discount, total, delivery_date, delivery_address, note, created_at, updated_at
FROM orders
ORDER BY created_at DESC, id
LIMIT $1 OFFSET $2
`

type ListOrdersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Danh sách đơn hàng cho admin, phân trang (mới nhất trước).
func (q *Queries) ListOrders(ctx context.Context, arg ListOrdersParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrders, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.CustomerID,
			&i.Channel,
			&i.Status,
			&i.Subtotal,
			&i.Discount,
			&i.Total,
			&i.DeliveryDate,
			&i.DeliveryAddress,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibleProducts = `-- name: ListVisibleProducts :many
SELECT id, slug, name, description, price, type, status, image_url, display_order, created_at, updated_at, badge, compare_at_price, subtitle
FROM products
WHERE status != 'hidden'
ORDER BY display_order, created_at, id
`

// Sản phẩm public: ẩn status='hidden', sắp theo thứ tự hiển thị rồi thời gian tạo
// (REQ-PROD-001).
func (q *Queries) ListVisibleProducts(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, listVisibleProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.Type,
			&i.Status,
			&i.ImageUrl,
			&i.DisplayOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Badge,
			&i.CompareAtPrice,
			&i.Subtitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockLead = `-- name: LockLead :one
SELECT id, name, phone, message, product_interest, source, status, created_at, order_id
FROM leads
WHERE id = $1
FOR UPDATE
`

// Khóa dòng lead (FOR UPDATE) ở đầu transaction convert để request convert song
// song cùng lead phải xếp hàng: request thứ 2 block tới khi request 1 commit rồi
// mới đọc được order_id đã set → guard WHERE order_id IS NULL loại nó (REQ-LEAD-005).
func (q *Queries) LockLead(ctx context.Context, id pgtype.UUID) (Lead, error) {
	row := q.db.QueryRow(ctx, lockLead, id)
	var i Lead
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Message,
		&i.ProductInterest,
		&i.Source,
		&i.Status,
		&i.CreatedAt,
		&i.OrderID,
	)
	return i, err
}

const setLeadOrder = `-- name: SetLeadOrder :execrows
UPDATE leads
SET status = 'converted', order_id = $2
WHERE id = $1 AND order_id IS NULL
`

type SetLeadOrderParams struct {
	ID      pgtype.UUID `json:"id"`
	OrderID pgtype.UUID `json:"order_id"`
}

// Convert lead → đơn: gắn order_id + đánh dấu 'converted' CHỈ khi lead chưa convert
// (order_id IS NULL). Guard nằm trong điều kiện WHERE (atomic trong tx) — chống race
// convert-2-lần tạo đơn mồ côi. Trả số dòng ảnh hưởng: 0 = đã convert trước đó
// (REQ-LEAD-005).
func (q *Queries) SetLeadOrder(ctx context.Context, arg SetLeadOrderParams) (int64, error) {
	result, err := q.db.Exec(ctx, setLeadOrder, arg.ID, arg.OrderID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sumRevenueThisMonth = `-- name: SumRevenueThisMonth :one
SELECT coalesce(sum(total), 0)::bigint
FROM orders
WHERE status = 'done'
  AND created_at >= date_trunc('month', now() AT TIME ZONE 'Asia/Ho_Chi_Minh')
                     AT TIME ZONE 'Asia/Ho_Chi_Minh'
`

// Doanh thu tháng hiện tại = tổng total các đơn đã 'done' tạo trong tháng, tính theo
// MÚI GIỜ VIỆT NAM (Asia/Ho_Chi_Minh). date_trunc trần chạy theo TZ server (UTC) →
// đơn done đặt sát nửa đêm đầu/cuối tháng giờ VN bị tính nhầm tháng. Đổi now() sang
// giờ VN, cắt về đầu tháng, rồi đổi ngược về timestamptz để so với created_at.
func (q *Queries) SumRevenueThisMonth(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, sumRevenueThisMonth)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateCustomer = `-- name: UpdateCustomer :one
UPDATE customers
SET name = $2, phone = $3, email = $4, company = $5, address = $6, type = $7, note = $8, updated_at = now()
WHERE id = $1
RETURNING id, name, phone, email, company, address, type, note, created_at, updated_at
`

type UpdateCustomerParams struct {
	ID      pgtype.UUID `json:"id"`
	Name    string      `json:"name"`
	Phone   *string     `json:"phone"`
	Email   *string     `json:"email"`
	Company *string     `json:"company"`
	Address *string     `json:"address"`
	Type    string      `json:"type"`
	Note    *string     `json:"note"`
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, updateCustomer,
		arg.ID,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.Company,
		arg.Address,
		arg.Type,
		arg.Note,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Company,
		&i.Address,
		&i.Type,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLeadStatus = `-- name: UpdateLeadStatus :one
UPDATE leads
SET status = $2
WHERE id = $1
RETURNING id, name, phone, message, product_interest, source, status, created_at, order_id
`

type UpdateLeadStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateLeadStatus(ctx context.Context, arg UpdateLeadStatusParams) (Lead, error) {
	row := q.db.QueryRow(ctx, updateLeadStatus, arg.ID, arg.Status)
	var i Lead
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Message,
		&i.ProductInterest,
		&i.Source,
		&i.Status,
		&i.CreatedAt,
		&i.OrderID,
	)
	return i, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, code, customer_id, channel, status, subtotal, discount, total, delivery_date, delivery_address, note, created_at, updated_at
`

type UpdateOrderStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.ID, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.CustomerID,
		&i.Channel,
		&i.Status,
		&i.Subtotal,
		&i.Discount,
		&i.Total,
		&i.DeliveryDate,
		&i.DeliveryAddress,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET slug = $2, name = $3, description = $4, price = $5, type = $6, status = $7,
    image_url = $8, display_order = $9, badge = $10, compare_at_price = $11,
    subtitle = $12, updated_at = now()
WHERE id = $1
RETURNING id, slug, name, description, price, type, status, image_url, display_order, created_at, updated_at, badge, compare_at_price, subtitle
`

type UpdateProductParams struct {
	ID             pgtype.UUID `json:"id"`
	Slug           string      `json:"slug"`
	Name           string      `json:"name"`
	Description    *string     `json:"description"`
	Price          int64       `json:"price"`
	Type           string      `json:"type"`
	Status         string      `json:"status"`
	ImageUrl       *string     `json:"image_url"`
	DisplayOrder   int32       `json:"display_order"`
	Badge          *string     `json:"badge"`
	CompareAtPrice *int64      `json:"compare_at_price"`
	Subtitle       *string     `json:"subtitle"`
}

// Cập nhật toàn bộ thuộc tính sản phẩm theo id (REQ-PROD-002).
func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.Price,
		arg.Type,
		arg.Status,
		arg.ImageUrl,
		arg.DisplayOrder,
		arg.Badge,
		arg.CompareAtPrice,
		arg.Subtitle,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.Price,
		&i.Type,
		&i.Status,
		&i.ImageUrl,
		&i.DisplayOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Badge,
		&i.CompareAtPrice,
		&i.Subtitle,
	)
	return i, err
}

const updateProductImage = `-- name: UpdateProductImage :exec
UPDATE products
SET image_url = $2, updated_at = now()
WHERE id = $1
`

type UpdateProductImageParams struct {
	ID       pgtype.UUID `json:"id"`
	ImageUrl *string     `json:"image_url"`
}

// Cập nhật ảnh sản phẩm sau khi upload thành công (REQ-PROD-003).
func (q *Queries) UpdateProductImage(ctx context.Context, arg UpdateProductImageParams) error {
	_, err := q.db.Exec(ctx, updateProductImage, arg.ID, arg.ImageUrl)
	return err
}
