/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Trả về trạng thái sống của service. Không chạm DB.
         */
        get: operations["getHealthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Danh sách sản phẩm public
         * @description Trả về sản phẩm đang hiển thị (ẩn status='hidden'), sắp theo thứ tự hiển thị. Public, không cần auth (REQ-PROD-001).
         */
        get: operations["listProducts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Tạo lead từ form liên hệ
         * @description Nhận dữ liệu form liên hệ public, validate (tên, SĐT Việt Nam, độ dài) và lưu lead trạng thái 'new'. Có rate limit theo IP để chống spam (REQ-LEAD-001/002/003, NFR-004).
         */
        post: operations["createLead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Product: {
            /** Format: uuid */
            id: string;
            slug: string;
            name: string;
            description?: string | null;
            /**
             * Format: int64
             * @description Giá VND, số nguyên
             */
            price: number;
            /** @enum {string} */
            type: "gift_box" | "single_cake";
            /** @enum {string} */
            status: "available" | "sold_out" | "hidden";
            image_url?: string | null;
            /** @description Nhãn marketing (vd "Bán chạy", "Mới"), null nếu không có */
            badge?: string | null;
            /**
             * Format: int64
             * @description Giá gốc để so sánh (VND). Nếu > price → hiện giá gạch + % giảm. Null nếu không khuyến mãi.
             */
            compare_at_price?: number | null;
            /** @description Nhãn phân loại nhỏ in hoa trên tên (vd "Hộp thiếc cao cấp"), null nếu không có */
            subtitle?: string | null;
            display_order: number;
        };
        LeadInput: {
            /** @description Tên khách hàng (bắt buộc) */
            name: string;
            /** @description Số điện thoại Việt Nam (bắt buộc) */
            phone: string;
            /** @description Lời nhắn */
            message?: string | null;
            /** @description Sản phẩm khách quan tâm */
            product_interest?: string | null;
        };
        LeadCreated: {
            /** Format: uuid */
            id: string;
        };
        Health: {
            /** @example ok */
            status: string;
        };
        Error: {
            error: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service khỏe mạnh */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    listProducts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Danh sách sản phẩm */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Product"][];
                };
            };
        };
    };
    createLead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LeadInput"];
            };
        };
        responses: {
            /** @description Lead đã được tạo */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeadCreated"];
                };
            };
            /** @description Dữ liệu vào không hợp lệ */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Gửi quá nhiều yêu cầu (rate limit) */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
